version: '3.8'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: redis
    command: [ "redis-server", "--save", '""' ]
