version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: redis
    command: [ "redis-server", "--save", '""' ]

networks:
  default:
    name: qdvs_network
